# Generated by Django 5.2.13 on 2026-04-29 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField()),
                ('output_text', models.TextField(blank=True)),
                ('request_type', models.CharField(choices=[('resume', 'Resume'), ('summary', 'Summary')], default='resume', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Request',
                'verbose_name_plural': 'AI Requests',
                'db_table': 'core_ai_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
