# Generated by Django 5.2.13 on 2026-04-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_airequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='airequest',
            name='ai_response',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
